"""Reproducible-document 'tangle' step (the Python/Sweave pattern). Reads the
WeightWatcher-replication CSVs and emits, from data:
  - paper/figures/fig_*.png            (seaborn, via benchmarks/make_paper_figures)
  - paper/generated_values.tex         (\newcommand macros for every headline number)
  - paper/generated_tables.tex         (the full per-model + GPT-detail LaTeX tables)
The paper \input's the two .tex files and \includegraphics the figures, so re-running
`bash paper/build.sh` reweaves all numbers, tables, and figures from the CSVs --
nothing in the manuscript is hand-transcribed.

Run via build.sh (uv run --extra benchmarks python paper/generate.py).
"""
import sys
from pathlib import Path
import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "benchmarks"))
import make_paper_figures as mpf

DATA = Path("/data/mhough/wwj_ww_replication")
VGG = mpf.VGG
GPT = mpf.GPT


def _m(name, val):
    return f"\\newcommand{{\\{name}}}{{{val}}}\n"


def values_tex() -> str:
    s = pd.read_csv(DATA / "ww_replication_summary.csv").set_index("model")
    out = ["% AUTO-GENERATED by paper/generate.py -- do not edit by hand.\n"]
    # GPT means freq/bayes
    for m, tag in [("openai-gpt", "Gpt"), ("gpt2", "GptTwo"), ("gpt2-medium", "GptTwoMed")]:
        out.append(_m(f"ww{tag}Freq", f"{s.loc[m,'mean_alpha_freq']:.2f}"))
        out.append(_m(f"ww{tag}Bayes", f"{s.loc[m,'mean_alpha_bayes']:.2f}"))
    gap_f = s.loc["openai-gpt", "mean_alpha_freq"] - s.loc["gpt2", "mean_alpha_freq"]
    gap_b = s.loc["openai-gpt", "mean_alpha_bayes"] - s.loc["gpt2", "mean_alpha_bayes"]
    out.append(_m("wwGptGapFreq", f"{gap_f:.2f}"))
    out.append(_m("wwGptGapBayes", f"{gap_b:.2f}"))
    out.append(_m("wwGptGapShrink", f"{gap_f/gap_b:.1f}"))
    # VGG correlations (mean weighted-alpha vs acc)
    d = mpf._vgg_alpha_hat()
    rb = np.corrcoef(d["ahat"], d["acc"])[0, 1]; rf = np.corrcoef(d["ahat_f"], d["acc"])[0, 1]
    out.append(_m("wwVggRFreq", f"{rf:.2f}"))
    out.append(_m("wwVggRBayes", f"{rb:.2f}"))
    rmean = np.corrcoef([s.loc[m, "mean_alpha_bayes"] for m in VGG], list(VGG.values()))[0, 1]
    out.append(_m("wwVggRUnweighted", f"{rmean:+.2f}"))
    # BN PL-rejection range
    bn = [s.loc[m, "frac_pl_rejected"] for m in VGG if "bn" in m]
    out.append(_m("wwBnRejLo", f"{min(bn)*100:.0f}"))
    out.append(_m("wwBnRejHi", f"{max(bn)*100:.0f}"))
    # GPT detail: TPL win count, ppc range, ROPE, prior-sens, BF ranges
    bd = pd.read_csv(DATA / "openai-gpt_bayes_diagnostics.csv")
    gd = pd.read_csv(DATA / "openai-gpt_gptdetail.csv")
    big = gd[gd["alpha_freq"] > 5.0]
    out.append(_m("wwGptBigN", f"{len(big)}"))
    out.append(_m("wwGptTplWin", f"{int((bd['logbf_pl_vs_tpl']<0).sum())}"))
    out.append(_m("wwGptNlayers", f"{len(bd)}"))
    out.append(_m("wwGptBigAlphaFreqLo", f"{big['alpha_freq'].min():.1f}"))
    out.append(_m("wwGptBigAlphaFreqHi", f"{big['alpha_freq'].max():.1f}"))
    out.append(_m("wwGptBigAlphaBayesLo", f"{big['alpha_bayes'].min():.1f}"))
    out.append(_m("wwGptBigAlphaBayesHi", f"{big['alpha_bayes'].max():.1f}"))
    out.append(_m("wwGptPpcLo", f"{big['ppc_pvalue'].min():.2f}"))
    out.append(_m("wwGptPpcHi", f"{big['ppc_pvalue'].max():.2f}"))
    out.append(_m("wwGptBfExpLo", f"{int(big['logbf_pl_vs_exp'].min())}"))
    out.append(_m("wwGptBfExpHi", f"{int(big['logbf_pl_vs_exp'].max())}"))
    out.append(_m("wwGptXminShareLo", f"{int(big['xmin_var_share'].min()*100)}"))
    out.append(_m("wwGptXminShareHi", f"{int(big['xmin_var_share'].max()*100)}"))
    out.append(_m("wwGptRopeN", f"{int((bd['prob_in_rope2']>0.5).sum())}"))
    out.append(_m("wwGptPriorSens", f"{bd['prior_sens'].mean():.3f}"))
    return "".join(out)


def tables_tex() -> str:
    s = pd.read_csv(DATA / "ww_replication_summary.csv")
    cols = {"model": "Model", "n_layers": "$L$", "mean_alpha_freq": r"$\bar\alpha_{\rm freq}$",
            "mean_alpha_bayes": r"$\bar\alpha_{\rm bayes}$", "mean_ci_width": "CI width",
            "frac_pl_rejected": "PL-rej.", "published_top1": "top-1"}
    t = s[list(cols)].copy()
    t["frac_pl_rejected"] = (t["frac_pl_rejected"] * 100).round(0).astype(int).astype(str) + r"\%"
    t["published_top1"] = t["published_top1"].map(lambda v: f"{v:.1f}" if pd.notna(v) else "--")
    for c in ("mean_alpha_freq", "mean_alpha_bayes", "mean_ci_width"):
        t[c] = t[c].map(lambda v: f"{v:.2f}")
    t = t.rename(columns=cols)
    t["Model"] = t["Model"].str.replace("_", r"\_", regex=False)   # underscores in text mode
    tab1 = t.to_latex(index=False, escape=False, column_format="lcccccc")

    gd = pd.read_csv(DATA / "openai-gpt_gptdetail.csv")
    big = gd[gd["alpha_freq"] > 5.0].sort_values("alpha_freq", ascending=False)
    g = big[["shape", "alpha_freq", "alpha_bayes", "ci_low", "ci_high",
             "xmin_var_share", "logbf_pl_vs_exp", "ppc_pvalue"]].copy()
    g.columns = ["shape", r"$\alpha_{\rm f}$", r"$\alpha_{\rm b}$", "CI lo", "CI hi",
                 "win.var", "logBF$_{\\rm exp}$", "ppc $p$"]
    for c in g.columns[1:]:
        g[c] = g[c].map(lambda v: f"{v:.2f}")
    tab2 = g.to_latex(index=False, escape=False, column_format="lccccccc")

    return ("% AUTO-GENERATED by paper/generate.py.\n"
            "\\newcommand{\\wwSummaryTable}{" + tab1 + "}\n"
            "\\newcommand{\\wwGptDetailTable}{" + tab2 + "}\n")


def main():
    mpf.make_all(HERE / "figures")
    (HERE / "generated_values.tex").write_text(values_tex())
    (HERE / "generated_tables.tex").write_text(tables_tex())
    print("generated: figures/, generated_values.tex, generated_tables.tex")


if __name__ == "__main__":
    main()
